### ISSUE TITLE
Bear is capturing the makefile macro, not the compiler

### ISSUE THREAD

**Issue by TomMD** [rizsotto/Bear#211] opened 2018-05-17 21:13 UTC
If you attach log output, please consider to run Bear with `-vvvv` to have debug logs available.

### Expected Behavior

I expected `bear make` to capture the compiler commands (ex: `g++` or `clang++` or `g++-6`) but instead it captured `c++` as the first element in the arugment list and has no command.

    git clone https://github.com/expensify/bedrock
    cd bedrock
    bear make
    less compile_commands.json

### Environment

- OS name & version: Ubuntu 16.04
- Bear version: 2.3.11
- Any reference to the project that you running against: expensify/bedrock
- Any information about the compiler that this project is using: g++-6

**Comment by rizsotto** [comment] 2018-05-18 01:32
Hey Tom, thanks for the report. I'm not sure I fully understand the problem... But trying to answer it. :)

Compilation database used by clang based tools are ignoring the compiler name. (Tools like `clang-tidy` or `clang-format`.) So, for them it's irrelevant that your compiler is `c++` or `g++-6`. These tools will replace the compiler name to `clang`. (Their only interest is to know the difference between a `cc` and a `c++` call.) So, this is a feature not a bug. :)

Compilation database specification allows to use `command` or `arguments` attributes. They mean the same thing. Except `command` is needs to be shell escaped, while the `arguments` remains a list (and JSON escapes it). The `arguments` is easier to implement, that's why Bear uses it. (Learned that shell escaping can be difficult from many bug reports.) If you want to have the `command` version, you need to convert to it. (You can try https://github.com/Sarcasm/compdb to convert Bear output to your desired format.)

**Comment by rizsotto** [comment] 2018-05-18 03:46
Ok, understand it better now. But I'm still missing what are you using the compilation database? If you use tools which based on clang tooling library, those will ignore the gnu-only flags. If you use it to re-run the command that will need a hack. :)

I'm hesitant to put the original compiler into the compilation database, because it might be difficult for those who have weird compiler names and currently Bear fix it for them. To make it configurable is an option. (Like `--keep-compiler-name` as an extra parameter.) What would you say?

As a workaround I suggest to edit the python file (`bear/main.py.in`) around line 515, the function which separates the compiler from the rest of the arguments.

**Comment by lyonlh** [comment] 2018-05-18 05:37
Not sure if self-promotion is welcomed here, but captruing the original compilation info and putting it to compilation database are what I've done in [https://github.com/lyonlh/ABCD](https://github.com/lyonlh/ABCD).

**Comment by TomMD** [comment] 2018-05-18 18:47
@rizsotto 

>  what are you using the compilation database?

Infer, the tool, consumes compilation databases and reproduces the build while simultaneously performing a static analysis. This is not possible if the compilation database does not include the compiler used since there are functional differences between clang++ and g++ (for example).  In other words, the concept of a compilation database has caught on and grown outside of the clang community, which is good but that growth and generalized use causes more issues such as this one.

I'd be quite happy with a flag, such as `--keep-compiler-name`.  Would that produce a `command` field?  I'll look at the indicated file and experiment, thanks for the pointer.

@lyonlh I'll look, thanks.

**Comment by rizsotto** [comment] 2018-05-19 11:10
Cool, I have not heard about infer before. :) But it looks that they wrote another intercept tool too. Just for curiosity why did you decided to use Bear instead of the infer tool?

The `command` field you can get with the `compdb` tool. (I did linked the repo earlier.) To be very fast, you can `sed -i -e 's/c++/g++/g' compilation_database.json` and then `compdb`can give you the `command` filed. :)

**Comment by TomMD** [comment] 2018-05-19 23:59
> Cool, I have not heard about infer before. :) But it looks that they wrote another intercept tool too. Just for curiosity why did you decided to use Bear instead of the infer tool?

Their intercept tool is buggy.  Sometimes that works, sometimes bear + `infer run --compilation-database ...` works better. In this case, bear fails but if I can have one path that always works then the world will be a better place.  I actually run one (ex: bear ; infer) and if that fails then try the other, but that's a cludgy hack.

I appreciate the compdb pointer. I  can't `sed` since the automated script doesn't know if `c++` should be `clang++` or `g++` or `g++-6` or something else for any given project, and avoiding manual intervention is the whole point.

**Comment by rizsotto** [comment] 2018-05-20 07:40
Was checking Infer compilation [parser](https://github.com/facebook/infer/blob/master/infer/src/integration/CompilationDatabase.ml#L38) does accept both `arguments` and `command`. You don't need to use `compdb` to convert it.

**Comment by rizsotto** [comment] 2018-07-29 12:01
Fixed. Will be released under version 2.3.12.

**Closed by rizsotto** 2018-07-29 12:01 UTC
Labels: bug, enhancement

**Comment by TomMD** [comment] 2018-07-29 13:37
Thank you so much
