### ISSUE TITLE
quote bug

### ISSUE THREAD

**Issue by aamen110** [rizsotto/Bear#96] opened 2015-08-19 09:40 UTC
for the bear
when I pass -DMODULE_SCOPE=extern\ __attribute__\(\(__visibility__\(\"hidden\"\)\)\)  (in makefile)
I get  \"-DMODULE_SCOPE=extern __attribute__((__visibility__(\\\"hidden\\\")))\" in the json file
it is wrong
I find the function to the problem
    def quote(arg):
        table = {'\\': '\\\\', '"': '\\"', "'": "\\'"}
        return '"' + ''.join([table.get(c, c) for c in arg]) + '"'

what is the role of this  function  ?

**Comment by rizsotto** [comment] 2015-08-19 14:00
thanks for the report, there are problems with the correct escaping in Bear, which i am aware of. but this one you mentioned is not a bug/problem i think. simple when you pass the literal with space to the shell it could be either quoted `"like this"` or escaped the space character `like\ this`. therefore the two -you've mentioned- are the same.
will work to fix the correct shell+JSON encoding as it should be in a compilation database. but there are already a ticket for that. and i will close this one.

**Closed by rizsotto** 2015-08-19 14:00 UTC
