### ISSUE TITLE
Regression: Version 3.x fails to produce output for the Linux kernel on ARM but version 2.x works fine

### ISSUE THREAD

**Issue by ljanyst** [rizsotto/Bear#367] opened 2021-03-20 10:16 UTC
**Describe the bug**
When using version 3, I don't seem to be able to force the tool to use the library preload method. It seems to use the wrapper no matter what I do. This slows down the compilation of the Linux kernel ~5 times (from about 1.5 hours to around 7 hours), produces 1.5 GB worth of an SQLite file. This SQLite file is then processed for ~8 hours and results in an empty `compile_commands.json`. Using the latest 2.x version compiled from source produces the correct result without noticeable slowdown over the regular compilation.

**To Reproduce**
On Arm:

```
wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.11.7.tar.xz
tar xf linux-5.11.7.tar.xz
cd linux-5.11.7
make defconfig
bear -- make -j12 Image modules
```

**Expected behavior**
Produces correct `compile_commands.json` in a reasonable time just like the version 2.x does.

**Environment:**
 - OS name: Linux
 - OS version: [Debian testing] 
 - OS architecture: aarch64
 - Bear version: 3.0.8
 - Bear install method: apt-get

**Comment by rizsotto** [comment] 2021-03-20 12:39
Hi @ljanyst , thanks for the report. I think this problem has the same root cause as the #350 . Will close it and track it there.

**Closed by rizsotto** 2021-03-20 12:39 UTC

**Comment by rizsotto** [comment] 2021-03-23 00:37
Hi @ljanyst , could you give a try to the 3.0.10 version? It contains fixes for memory allocation and computational complexity. It might be still slower than the 2.4 version was. I would like to hear if this is improved on ARM, which I have no access to.

**Comment by ljanyst** [comment] 2021-03-25 07:12
Thank you so much for having a look at @rizsotto ! Here are some measurements:

No Bear:

```
make -j12 Image modules  18230.87s user 1785.97s system 560% cpu 59:29.33 total
```

Bear 2.4:

```
bear --libear /blah/libear.so make     18832.85s user 1910.97s system 540% cpu 1:03:55.24 total
```

Bear 3.1:

```
bear -- make -j12 Image modules  23437.37s user 3796.72s system 153% cpu 4:55:01.59 total
```

Bear 3.10 is 5 times slower than Bear 2.x, and Bear 2.x ads barely noticeable overhead over the vanilla compilation. Having a closer look, Bear 3.10 spends some 1.5 hours actually compiling things and 3.5 hours processing the SQLite file it produces. The program that does the processing (I forgot the name) takes about 5% of the CPU and spends most of its time in the D-state (uninterruptible sleep due to IO). Note that the system this runs on has spinning disks, a software RAID5 on top of them, and a LUKS-encripted block device built on top of the RAID. I would, therefore, without looking at the code at all, assume that the problem is in the way you process records in the SQLite file. Very probably you mark a record as done in the database, this causes SQLite to issue a sync. It's fine on an SSD, but with spinning disks and all this RAID/encryption goodness it's actually very expensive. I hope this helps. Thank you very much for your time!

**Comment by rizsotto** [comment] 2021-03-25 08:24
Thanks @ljanyst for your analysis. I have to agree. During this week I was compile the Linux kernel multiple times with different SQLite settings. And my conclusion was the same about the IO bottleneck introduced by SQLite. I will focus on this aspect for the next release. Thank you again!
