### ISSUE TITLE
Not working in OSX Mojave

### ISSUE THREAD

**Issue by hessryanm** [rizsotto/Bear#232] opened 2019-01-04 22:59 UTC
If you attach log output, please consider to run Bear with `-vvvv` to have debug logs available.

I disabled SIP (based on the "known issues" with OS X), and now every time I try to run bear I get the issue:

> dyld: warning: could not load inserted library '/usr/local/lib/bear/libear.dylib' into hardened process because no suitable image found.  Did find:
> 	/usr/local/lib/bear/libear.dylib: code signature in (/usr/local/lib/bear/libear.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
> 	/usr/local/lib/bear/libear.dylib: stat() failed with errno=1

From reading online it looks like the code has to be updated in some way for Mojave, as relates to this code-signing.

### Environment

- OS name & version: OS X Mojave 10.14.2
- Bear version: bear 2.3.13
- Any reference to the project that you running against:
- Any information about the compiler that this project is using: Apple LLVM version 10.0.0 (clang-1000.11.45.5)

**Comment by rizsotto** [comment] 2019-01-05 22:52
Hi Ryan, thanks for the report. I can't reproduce it by myself. (have no access to mac machnes.) So I might need your help to fix this.
- Did you installed Bear from brew or from sources?
- After you installed Bear, did you update your XCode to a newer version? (Might want to recompile/reinstall with the new tools?)
- Another trick I've found on other project suffering with this error message. If a project was compiled for 32 and 64 bit platform, it was fixing the problem by compile the library to only one architecture. For OSX Bear use `CMAKE_OSX_ARCHITECTURES` line in the `CMakeLists.txt` file. Could you try to change (or remove) that line when building it?

**Comment by hessryanm** [comment] 2019-01-07 22:48
1: I have tried both from brew as well as from source.  Both exhibit this behavior.
2: I already have the newest version of XCode installed, along with command line tools.
3: After removing that line from from CMakeLists.txt I deleted everything in my build directory, then rebuilt completely.  The error persists.

When I re-ran the cmake command (listed first in the README), I got the following warning:
```
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   ear

This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by rizsotto** [comment] 2019-01-07 23:37
Thanks to come back with your findings. I was trying to google about the error message you sent. Found that this is a kind of common problem with shared object loading on OSX Mojave. The most relevant page I've found was [this](http://www.lapcatsoftware.com/articles/debugging-mojave.html). Unfortunately I've not find any good workaround yet.

New version of Bear (which I am working on) plan to use compiler wrappers, which will not have this kind of error. (Not sure about the release date yet.)

**Comment by hessryanm** [comment] 2019-01-08 17:59
Well, darn, thanks for checking!  I guess I'll just have to wait for the new version...

**Comment by rizsotto** [comment] 2019-07-30 12:26
Closing it because the new version work is tracked elsewhere. There are workarounds mentioned in this other ticket. #215

**Closed by rizsotto** 2019-07-30 12:26 UTC

**Comment by xnxin** [comment] 2019-08-02 01:18
Same problem, and checkout issue #215 , still not resolved.
