### ISSUE TITLE
Linking is not included in database

### ISSUE THREAD

**Issue by ochipara** [rizsotto/Bear#230] opened 2018-12-11 15:10 UTC
If you attach log output, please consider to run Bear with `-vvvv` to have debug logs available.

### Expected Behavior
I am trying to construct a compilation database for nginx (1.15.7) using bear. Bear is doing nicely in recording all the objects that are derived, however, it does not include the linking command. So, I was expecting to get an entry for the execution of 

cc -o objs/nginx \
        objs/src/core/nginx.o \
        objs/src/core/ngx_log.o \
       [... lots of object files omitted her]
        -L/usr/local/lib -lpcre -lz

### Actual Behavior
No linking entry included in the compilation database. From the logs, it seems that the command is parsed but not saved.

bear: DEBUG: parse_exec_trace: parse exec trace file: /var/folders/8y/7qxbfzr90v79bk1b737tzb553ryznd/T/intercept-h4pf7o94/execution.NRMYAw
bear: DEBUG: _split_command: input was: ['cc', '-o', 'objs/nginx', 'objs/src/core/nginx.o', 'objs/src/core/ngx_log.o', 'objs/src/core/ngx_palloc.o', 'objs/src/core/ngx_array.o', 'objs/src/core/ngx_list.o', 'objs/src/core/ngx_hash.o', 'objs/src/core/ngx_buf.o', 'objs/src/core/ngx_queue.o', 'objs/src/core/ngx_output_chain.o', 'objs/src/core/ngx_string.o', 'objs/src/core/ngx_parse.o', 'objs/src/core/ngx_parse_time.o', 'objs/src/core/ngx_inet.o', 'objs/src/core/ngx_file.o', 'objs/src/core/ngx_crc32.o', 'objs/src/core/ngx_murmurhash.o', 'objs/src/core/ngx_md5.o', 'objs/src/core/ngx_sha1.o', 'objs/src/core/ngx_rbtree.o', 'objs/src/core/ngx_radix_tree.o', 'objs/src/core/ngx_slab.o', 'objs/src/core/ngx_times.o', 'objs/src/core/ngx_shmtx.o', 'objs/src/core/ngx_connection.o', 'objs/src/core/ngx_cycle.o', 'objs/src/core/ngx_spinlock.o', 'objs/src/core/ngx_rwlock.o', 'objs/src/core/ngx_cpuinfo.o', 'objs/src/core/ngx_conf_file.o', 'objs/src/core/ngx_module.o', 'objs/src/core/ngx_resolver.o', 'objs/src/core/ngx_open_file_cache.o', 'objs/src/core/ngx_crypt.o', 'objs/src/core/ngx_proxy_protocol.o', 'objs/src/core/ngx_syslog.o', 'objs/src/event/ngx_event.o', 'objs/src/event/ngx_event_timer.o', 'objs/src/event/ngx_event_posted.o', 'objs/src/event/ngx_event_accept.o', 'objs/src/event/ngx_event_udp.o', 'objs/src/event/ngx_event_connect.o', 'objs/src/event/ngx_event_pipe.o', 'objs/src/os/unix/ngx_time.o', 'objs/src/os/unix/ngx_errno.o', 'objs/src/os/unix/ngx_alloc.o', 'objs/src/os/unix/ngx_files.o', 'objs/src/os/unix/ngx_socket.o', 'objs/src/os/unix/ngx_recv.o', 'objs/src/os/unix/ngx_readv_chain.o', 'objs/src/os/unix/ngx_udp_recv.o', 'objs/src/os/unix/ngx_send.o', 'objs/src/os/unix/ngx_writev_chain.o', 'objs/src/os/unix/ngx_udp_send.o', 'objs/src/os/unix/ngx_udp_sendmsg_chain.o', 'objs/src/os/unix/ngx_channel.o', 'objs/src/os/unix/ngx_shmem.o', 'objs/src/os/unix/ngx_process.o', 'objs/src/os/unix/ngx_daemon.o', 'objs/src/os/unix/ngx_setaffinity.o', 'objs/src/os/unix/ngx_setproctitle.o', 'objs/src/os/unix/ngx_posix_init.o', 'objs/src/os/unix/ngx_user.o', 'objs/src/os/unix/ngx_dlopen.o', 'objs/src/os/unix/ngx_process_cycle.o', 'objs/src/os/unix/ngx_darwin_init.o', 'objs/src/event/modules/ngx_kqueue_module.o', 'objs/src/os/unix/ngx_darwin_sendfile_chain.o', 'objs/src/core/ngx_regex.o', 'objs/src/http/ngx_http.o', 'objs/src/http/ngx_http_core_module.o', 'objs/src/http/ngx_http_special_response.o', 'objs/src/http/ngx_http_request.o', 'objs/src/http/ngx_http_parse.o', 'objs/src/http/modules/ngx_http_log_module.o', 'objs/src/http/ngx_http_request_body.o', 'objs/src/http/ngx_http_variables.o', 'objs/src/http/ngx_http_script.o', 'objs/src/http/ngx_http_upstream.o', 'objs/src/http/ngx_http_upstream_round_robin.o', 'objs/src/http/ngx_http_file_cache.o', 'objs/src/http/ngx_http_write_filter_module.o', 'objs/src/http/ngx_http_header_filter_module.o', 'objs/src/http/modules/ngx_http_chunked_filter_module.o', 'objs/src/http/modules/ngx_http_range_filter_module.o', 'objs/src/http/modules/ngx_http_gzip_filter_module.o', 'objs/src/http/ngx_http_postpone_filter_module.o', 'objs/src/http/modules/ngx_http_ssi_filter_module.o', 'objs/src/http/modules/ngx_http_charset_filter_module.o', 'objs/src/http/modules/ngx_http_userid_filter_module.o', 'objs/src/http/modules/ngx_http_headers_filter_module.o', 'objs/src/http/ngx_http_copy_filter_module.o', 'objs/src/http/modules/ngx_http_not_modified_filter_module.o', 'objs/src/http/modules/ngx_http_static_module.o', 'objs/src/http/modules/ngx_http_autoindex_module.o', 'objs/src/http/modules/ngx_http_index_module.o', 'objs/src/http/modules/ngx_http_mirror_module.o', 'objs/src/http/modules/ngx_http_try_files_module.o', 'objs/src/http/modules/ngx_http_auth_basic_module.o', 'objs/src/http/modules/ngx_http_access_module.o', 'objs/src/http/modules/ngx_http_limit_conn_module.o', 'objs/src/http/modules/ngx_http_limit_req_module.o', 'objs/src/http/modules/ngx_http_geo_module.o', 'objs/src/http/modules/ngx_http_map_module.o', 'objs/src/http/modules/ngx_http_split_clients_module.o', 'objs/src/http/modules/ngx_http_referer_module.o', 'objs/src/http/modules/ngx_http_rewrite_module.o', 'objs/src/http/modules/ngx_http_proxy_module.o', 'objs/src/http/modules/ngx_http_fastcgi_module.o', 'objs/src/http/modules/ngx_http_uwsgi_module.o', 'objs/src/http/modules/ngx_http_scgi_module.o', 'objs/src/http/modules/ngx_http_memcached_module.o', 'objs/src/http/modules/ngx_http_empty_gif_module.o', 'objs/src/http/modules/ngx_http_browser_module.o', 'objs/src/http/modules/ngx_http_upstream_hash_module.o', 'objs/src/http/modules/ngx_http_upstream_ip_hash_module.o', 'objs/src/http/modules/ngx_http_upstream_least_conn_module.o', 'objs/src/http/modules/ngx_http_upstream_random_module.o', 'objs/src/http/modules/ngx_http_upstream_keepalive_module.o', 'objs/src/http/modules/ngx_http_upstream_zone_module.o', 'objs/ngx_modules.o', '-L/usr/local/lib', '-lpcre', '-lz']
bear: DEBUG: _split_command: output is: CompilationCommand(compiler='cc', language=0, phase=[], flags=['objs/src/core/nginx.o', 'objs/src/core/ngx_log.o', 'objs/src/core/ngx_palloc.o', 'objs/src/core/ngx_array.o', 'objs/src/core/ngx_list.o', 'objs/src/core/ngx_hash.o', 'objs/src/core/ngx_buf.o', 'objs/src/core/ngx_queue.o', 'objs/src/core/ngx_output_chain.o', 'objs/src/core/ngx_string.o', 'objs/src/core/ngx_parse.o', 'objs/src/core/ngx_parse_time.o', 'objs/src/core/ngx_inet.o', 'objs/src/core/ngx_file.o', 'objs/src/core/ngx_crc32.o', 'objs/src/core/ngx_murmurhash.o', 'objs/src/core/ngx_md5.o', 'objs/src/core/ngx_sha1.o', 'objs/src/core/ngx_rbtree.o', 'objs/src/core/ngx_radix_tree.o', 'objs/src/core/ngx_slab.o', 'objs/src/core/ngx_times.o', 'objs/src/core/ngx_shmtx.o', 'objs/src/core/ngx_connection.o', 'objs/src/core/ngx_cycle.o', 'objs/src/core/ngx_spinlock.o', 'objs/src/core/ngx_rwlock.o', 'objs/src/core/ngx_cpuinfo.o', 'objs/src/core/ngx_conf_file.o', 'objs/src/core/ngx_module.o', 'objs/src/core/ngx_resolver.o', 'objs/src/core/ngx_open_file_cache.o', 'objs/src/core/ngx_crypt.o', 'objs/src/core/ngx_proxy_protocol.o', 'objs/src/core/ngx_syslog.o', 'objs/src/event/ngx_event.o', 'objs/src/event/ngx_event_timer.o', 'objs/src/event/ngx_event_posted.o', 'objs/src/event/ngx_event_accept.o', 'objs/src/event/ngx_event_udp.o', 'objs/src/event/ngx_event_connect.o', 'objs/src/event/ngx_event_pipe.o', 'objs/src/os/unix/ngx_time.o', 'objs/src/os/unix/ngx_errno.o', 'objs/src/os/unix/ngx_alloc.o', 'objs/src/os/unix/ngx_files.o', 'objs/src/os/unix/ngx_socket.o', 'objs/src/os/unix/ngx_recv.o', 'objs/src/os/unix/ngx_readv_chain.o', 'objs/src/os/unix/ngx_udp_recv.o', 'objs/src/os/unix/ngx_send.o', 'objs/src/os/unix/ngx_writev_chain.o', 'objs/src/os/unix/ngx_udp_send.o', 'objs/src/os/unix/ngx_udp_sendmsg_chain.o', 'objs/src/os/unix/ngx_channel.o', 'objs/src/os/unix/ngx_shmem.o', 'objs/src/os/unix/ngx_process.o', 'objs/src/os/unix/ngx_daemon.o', 'objs/src/os/unix/ngx_setaffinity.o', 'objs/src/os/unix/ngx_setproctitle.o', 'objs/src/os/unix/ngx_posix_init.o', 'objs/src/os/unix/ngx_user.o', 'objs/src/os/unix/ngx_dlopen.o', 'objs/src/os/unix/ngx_process_cycle.o', 'objs/src/os/unix/ngx_darwin_init.o', 'objs/src/event/modules/ngx_kqueue_module.o', 'objs/src/os/unix/ngx_darwin_sendfile_chain.o', 'objs/src/core/ngx_regex.o', 'objs/src/http/ngx_http.o', 'objs/src/http/ngx_http_core_module.o', 'objs/src/http/ngx_http_special_response.o', 'objs/src/http/ngx_http_request.o', 'objs/src/http/ngx_http_parse.o', 'objs/src/http/modules/ngx_http_log_module.o', 'objs/src/http/ngx_http_request_body.o', 'objs/src/http/ngx_http_variables.o', 'objs/src/http/ngx_http_script.o', 'objs/src/http/ngx_http_upstream.o', 'objs/src/http/ngx_http_upstream_round_robin.o', 'objs/src/http/ngx_http_file_cache.o', 'objs/src/http/ngx_http_write_filter_module.o', 'objs/src/http/ngx_http_header_filter_module.o', 'objs/src/http/modules/ngx_http_chunked_filter_module.o', 'objs/src/http/modules/ngx_http_range_filter_module.o', 'objs/src/http/modules/ngx_http_gzip_filter_module.o', 'objs/src/http/ngx_http_postpone_filter_module.o', 'objs/src/http/modules/ngx_http_ssi_filter_module.o', 'objs/src/http/modules/ngx_http_charset_filter_module.o', 'objs/src/http/modules/ngx_http_userid_filter_module.o', 'objs/src/http/modules/ngx_http_headers_filter_module.o', 'objs/src/http/ngx_http_copy_filter_module.o', 'objs/src/http/modules/ngx_http_not_modified_filter_module.o', 'objs/src/http/modules/ngx_http_static_module.o', 'objs/src/http/modules/ngx_http_autoindex_module.o', 'objs/src/http/modules/ngx_http_index_module.o', 'objs/src/http/modules/ngx_http_mirror_module.o', 'objs/src/http/modules/ngx_http_try_files_module.o', 'objs/src/http/modules/ngx_http_auth_basic_module.o', 'objs/src/http/modules/ngx_http_access_module.o', 'objs/src/http/modules/ngx_http_limit_conn_module.o', 'objs/src/http/modules/ngx_http_limit_req_module.o', 'objs/src/http/modules/ngx_http_geo_module.o', 'objs/src/http/modules/ngx_http_map_module.o', 'objs/src/http/modules/ngx_http_split_clients_module.o', 'objs/src/http/modules/ngx_http_referer_module.o', 'objs/src/http/modules/ngx_http_rewrite_module.o', 'objs/src/http/modules/ngx_http_proxy_module.o', 'objs/src/http/modules/ngx_http_fastcgi_module.o', 'objs/src/http/modules/ngx_http_uwsgi_module.o', 'objs/src/http/modules/ngx_http_scgi_module.o', 'objs/src/http/modules/ngx_http_memcached_module.o', 'objs/src/http/modules/ngx_http_empty_gif_module.o', 'objs/src/http/modules/ngx_http_browser_module.o', 'objs/src/http/modules/ngx_http_upstream_hash_module.o', 'objs/src/http/modules/ngx_http_upstream_ip_hash_module.o', 'objs/src/http/modules/ngx_http_upstream_least_conn_module.o', 'objs/src/http/modules/ngx_http_upstream_random_module.o', 'objs/src/http/modules/ngx_http_upstream_keepalive_module.o', 'objs/src/http/modules/ngx_http_upstream_zone_module.o', 'objs/ngx_modules.o'], files=[], output=['objs/nginx'])

### Environment

- OS name & version: Mojave (10.14.1)
- Bear version: bear 2.3.13
- Any reference to the project that you running against: nginx
- Any information about the compiler that this project is using: clang 7.0

**Comment by rizsotto** [comment] 2018-12-12 12:02
Hi @ochipara , thanks for the report. Yes, Bear does not put those compiler calls into the output which are pure linking.

The main reason for that, the compilation database does not instruct how that line shall looks like. This "feature" was asked a few years before. Then I did asked on the Clang mailing list from those who were defining it at the first place, but the answer was not straight that I can use as a guide to implement that. It also not clear how consumers of the compilation database would take that entry.

On the other hand, I'm currently working on a format that is _not_ the JSON compilation database, which might contain the linking too. Not sure that would help you now.

I'm curious, how would you like to see that entry in the compilation database? And tell me, how would you use such compilation database?

**Comment by ochipara** [comment] 2018-12-13 20:07
Hi,

I am working on a project where I am tool to insert instrumentation in C programs. I am using bear to generate a compilation database, then I am generating a ninja build file from the database. This way I can duplicate the build process. Right now I am extracting the linker commands by running bear with verbose output and then grepping for the relevant information (this is clearly a hack). 

grep "_split_command:.*clang.*objs/nginx.*-L" bear.out  | sort -u | python fix_link.py

This will generate an entry similar to those used for compilation:

{"arguments": ["/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang", 
"-o", "objs/nginx", 
"objs/src/core/nginx.o", 
... lots of committed object files ...
, "-L/usr/local/lib", "-lpcre", "-lz"], 
"directory": "<...>/nginx-1.15.7", 
"file": "objs/nginx"}

**Comment by rizsotto** [comment] 2018-12-14 06:05
Thanks to explaining @ochipara . I think your use case is totally valid. (I mentioned that I'm working on a new format that will help to do such task easier.) But the current compilation database output is defined by the Clang project. And it's intended to capture only the compilations.

The entry you've just showed is very different what compilations have.

1. the attribute `file` is used as the input of the compilation. Here it's more like an output of the linking.
1. there is an attribute `output` for output. Which is optional, so we can use that.
1. but the `file` has to be there, and it's a single string (not a list)

**Comment by rizsotto** [comment] 2019-07-30 12:30
Closing it, possible duplicate of #205

**Closed by rizsotto** 2019-07-30 12:30 UTC
Labels: duplicate
