### ISSUE TITLE
Does it make sense to make --append smarter?

### ISSUE THREAD

**Issue by wangnangg** [rizsotto/Bear#291] opened 2020-08-06 02:21 UTC
If compilation flags changed during incremental build, we will end up having multiple entries for the same file. I think this is undesired behavior. Does it make sense to replace the old entry with the new one for the same file?

If you think this change makes sense, I can submit a patch.

**Comment by rizsotto** [comment] 2020-08-06 10:57
Hey @wangnangg , I am aware of the problem. But don't know a good solution for it. Here is why...

None of the attributes of the compilation database entry are unique. To have the same source file twice (with different compiler flags) is completely legal. There are project which compiles the same modules twice, but with different compiler flags. (An example for that could be: you write an interface and you put the client and the server in the same module. And your build system compiles the same file twice, once with `-Dclient` and once with `-Dserver` flags.) So, because of this, it's not easy to know if the duplicate entry is caused by mistake or it's intended.

If you know a good solution for this problem, let me know.

**Comment by wangnangg** [comment] 2020-08-06 18:23
I see. I don't know a good solution. Just wonder how the language server makes use of the duplicated entries. Will it just arbitrarily pick one to use?

**Comment by rizsotto** [comment] 2020-08-06 22:48
I think the language server uses both. (Don't know for sure. But I don't see a reason why it shall not read all entries.)

But I have an idea to solve this problem. In the new version of Bear, the output field is also filled. And that shall be unique in the compilation database. I re-open this ticket then to implement it in the new version. (Will be released soon, I would not backport to the current master.)

**Closed** 2020-09-10 09:42 UTC
Labels: enhancement, area:output
