### ISSUE TITLE
ERROR: ld.so: object '/tmp/intercept-gsd6Ds/libear.so' from LD_PRELOAD cannot be preloaded: ignored.

### ISSUE THREAD

**Issue by ryosa** [rizsotto/Bear#187] opened 2017-10-31 05:02 UTC
I'm doing static analysis on a legacy project with `scan-build` but encountered errors due to bear settings like as many people reported. 

> make[3]: Entering directory `/root/ymph3/modules/3.10.5'
PATH=/opt/timesys/toolchains/x86_64-linux-463/core2duo/toolchain/bin:/sbin:/usr/sbin:/bin:/usr/bin;make -C /LinuxX86_64-Haswell/usr/src/linux-3.10.5 M=`pwd` V=1
ERROR: ld.so: object '/tmp/intercept-gsd6Ds/libear.so' from LD_PRELOAD cannot be preloaded: ignored.

Why does bear put libear.so in /tmp directory? And why is LD_PRELOAD invalid? It looks like libear.so doesn't exit in that directory.

Building and installing bear were as follows:

>   [root@baci build32]# cmake .. -DCMAKE_C_COMPILER_ARG1="-m32"; VERBOSE=1 make all
[root@baci build64]# cmake .. -DCMAKE_C_COMPILER_ARG1="-m64" -DDEFAULT_PRELOAD_FILE='/usr/local/lib64/libear.so'; VERBOSE=1 make all
[root@baci Bear]# install -m 0644 ./build32/libear/libear.so /usr/local/lib/libear.so
[root@baci Bear]# install -m 0644 ./build64/libear/libear.so /usr/local/lib64/libear.so
[root@baci Bear]# install -m 0555 ./build64/bear/bear /usr/local/bin/bear

It seems working.

> [root@baci Bear]# bear -h
usage: bear [-h] [--version] [--verbose] [--cdb <file>] [--use-cc <path>]
            [--use-c++ <path>] [--append] [--libear LIBEAR]
            ...
(snip)
  --libear LIBEAR, -l LIBEAR
                        specify libear file location. (default:
                        /usr/local/lib64/libear.so)

Before this, the default lib locations was /usr/local/lib, which emitted more errors than this.
I'm working on centos7 with a 32-bit toolchain, selinux disabled. 
Any suggestions are welcome. Thanks!

**Comment by rizsotto** [comment] 2017-10-31 09:00
Thanks to come back with your issue. It looks like you tried to follow the README file instructions about the multi-arch support. You've missed that the `DEFAULT_PRELOAD_FILE` parameter in your case shall be as `-DDDEFAULT_PRELOAD_FILE='/usr/local/$LIB/libear.so`. (Do not replace the `$LIB` string, it will be replaced by the dynamic linker, as explained in that section of the README file.)

**Comment by ryosa** [comment] 2017-10-31 23:58
@rizsotto Thanks, but that didn't solve the problem.

> [root@baci Bear]# bear -h
usage: bear [-h] [--version] [--verbose] [--cdb <file>] [--use-cc <path>]
            [--use-c++ <path>] [--append] [--libear LIBEAR]
            ...
(snip)
  --libear LIBEAR, -l LIBEAR
                        specify libear file location. (default:
                        /usr/local/$LIB/libear.so)

The result was the same.

> make[3]: Entering directory `/root/ymph3/modules/3.10.5'
PATH=/opt/timesys/toolchains/x86_64-linux-463/core2duo/toolchain/bin:/sbin:/usr/sbin:/bin:/usr/bin;make -C /LinuxX86_64-Haswell/usr/src/linux-3.10.5 M=`pwd` V=1
ERROR: ld.so: object '/tmp/intercept-KKpCEA/libear.so' from LD_PRELOAD cannot be preloaded: ignored.

I also tried `'-DDDEFAULT_PRELOAD_FILE='/$LIB/libear.so'` and didn't see any difference in the result.
Any other suggestions?

**Comment by rizsotto** [comment] 2017-11-01 04:20
You probably run some other `bear` than the one which you installed. (Maybe try `which bear` to find out which one you run.)

**Comment by ryosa** [comment] 2017-11-01 04:32
@rizsotto That's impossible, bear exists in no other place than /usr/local/bin.

**Comment by ryosa** [comment] 2017-11-01 06:19
Besides, I'm running `scan-build` which builds `libear.so.` I amended `intercept.py` just to see how `scan-build` builds `libear.so,` and found a 64-bit library was built in /tmp directory against 32-bit toolchain. Is that a right behaviour?

**Comment by rizsotto** [comment] 2017-11-01 10:48
Oh, that minor thing you could have mention before. ;) Here is what I recommend:
- use Bear to create compilation database. (You did not confirmed that command is working or not, but I presume if you installed it works.)
- run `analyze-build` against the project as a separate step. (Not `scan-build`, because you don't need to intercept the build command again. Compilation database already have the information how to compile the modules.)

**Comment by ryosa** [comment] 2017-11-02 00:21
@rizsotto Thanks for your advice. Running bear alone doesn't issue the LD_PRELOAD errors, but stops the compilation due to lack of shared object.

> make[2]: Entering directory `/root/Symphony3M/command'
/opt/timesys/toolchains/x86_64-linux-463/core2duo/toolchain/bin/ccache /opt/timesys/toolchains/x86_64-linux-463/core2duo/toolchain/bin/x86_64-timesys-linux-gnu-g++ -D_REENTRANT -D_PTHREADS -DLYNXOS -DLINUX -DSSLC_SMALL_CODE -DNO_SOFTWARE_CRYPTO -DTORNADO -DDEF_PPSystem -DDEF_ENGINE -DDEF_SupportSSD -DDEF_IWSCOPYJOB -DDEF_Soc1200 -DPMS_PP  -g -O2 -L/LinuxX86_64-Haswell/lib -L/LinuxX86_64-Haswell/usr/local/lib  -o usbhpd usbhpd.o myserver.o SocketConf.o UsbhpdConf.o -L/LinuxX86_64-Haswell/usr/local/libcont/5th/20170601/shlib -lrudiments -lshare_adapter -lpthread
/opt/timesys/toolchains/x86_64-linux-463/core2duo/toolchain/bin/../lib/gcc/x86_64-timesys-linux-gnu/4.6.3/../../../../x86_64-timesys-linux-gnu/bin/ld: cannot find -lshare_adapter

ld's behaviour is correct since libshare_adapter.so doesn't exist in my server. Does Bear allow `ld` to **link** to generate a compilation database?

**Comment by rizsotto** [comment] 2017-11-02 09:11
No, I don't think that this has to do anything with Bear. But you can validate it, by running the build command with and without Bear. If there is no difference between the runs, it's not Bear what is causing the problem.

**Comment by ryosa** [comment] 2017-11-03 01:47
Ok, understood. It would be more convenient if Bear generates a compilation DB without truly compiling and linking. : )

**Comment by rizsotto** [comment] 2017-11-03 09:48
Probably there are tools which works like that. Bear intercepts the actual compiler calls during the build... Will close this ticket, but feel free to reopen if you have question or problems.

**Closed by rizsotto** 2017-11-03 09:48 UTC

**Comment by ryosa** [comment] 2017-11-08 00:16
Hi. I want to pass parameters to `make` like `bear make -Bnk -j4`. How can I do it?
