### ISSUE TITLE
Autotools build fails to generate usable output on Solus Linux

### ISSUE THREAD

**Issue by Web-eWorks** [rizsotto/Bear#223] opened 2018-09-02 20:00 UTC
### Expected Behavior
Bear should be able to parse autotools builds.

### Actual Behavior
The autotools build system generates makefile compile commands that, while containing the compiler command, also do some shell preprocessing first. On my system, /bin/sh is statically linked (an OS-level decision), causing Bear to be unable to read the shell's invocation of GCC. Bear functions normally on Makefiles that call GCC directly, as the Make's invocation of /bin/sh can be intercepted by Bear.

The Makefile in question has this as it's compilation rule (I believe all automake builds generate this command):

```
$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
$(am__mv) $$depbase.Tpo $$depbase.Po
```

As far as I am aware, this is the standard (and unchangable) command generated by Automake. Ideally, Bear should be able to parse this command to extract the compile command from the rest of the shell invocation.

Specifically, all the information needed is in the second line - the `depbase` portions are used by the preprocessor to generate dependency information for the build system, and should have no effect on the output of the compile commands. A sample look at the files generated by Bear show that the above command generates the sequence `;\\\n` (JSON encoded) right before the actual compiler invocation, and `&&\\\n` afterwards.

### Environment

- OS name & version: Solus Linux (rolling release)
- Bear version: Latest (2473a67)
- Any reference to the project that you running against: [Pioneer](https://github.com/pioneerspacesim/pioneer)
- Any information about the compiler that this project is using: GCC 8.2.0

**Comment by Web-eWorks** [comment] 2018-09-02 23:32
I have tested it extensively to determine what the problem is. Here is the flow of the calls:

1. I (from an interactive shell) call `bear make`.
    - `make` is dynamically linked, and Bear generates debug output as appropriate. When a Makefile recipe calls `g++ ${WHATEVER}`, bear properly intercepts this
2. The Automake rules call a multi-line shell script as a single Make recipe line (see the backslashes at the end of the lines).
    - Make dispatches this, as with any other recipe line, to `/bin/sh`. `g++` is not at the start of the command, so Bear does not interpret this as a compiler call.
3. As my `/bin/sh` is statically linked, Bear cannot intercept the shell's `exec` calls, and does not know about the actual call to `g++`. Sub-make calls are inheriting the environment properly (I have confirmed Bear is generating the execution trace files for the calls to `/bin/sh`, even in sub-Makefiles), and non-Autotools builds comply perfectly with Bear, even when using sub-Makefiles.

**Comment by rizsotto** [comment] 2018-09-03 00:12
Thanks for the explanation. Statically linked binaries are getting more popular and bear is not ready to handle that. I'm working on to improve that... One approach that I'm implementing is to use compiler wrappers. So, statically linked binaries executing the wrappers (which will call the real compiler) can be intercepted. This work is targeted as 3.0 release.

**Comment by stanman29** [comment] 2018-11-10 00:52
I have a problem with building a compile_commands.json for the AROS project. It says it is an autotools project (configure.in) but it has a Metamake (mmake) tool that builds many of the project's makefiles. Does this effect the way your tool interacts with aros's build process and come up with an incomplete compile_commands.json file? 
I am trying to build the code browser Woboq which has errors building but am checking here first.
Woboq is dependent on the compile_commands.json file.
[aros-woboq.zip](https://github.com/rizsotto/Bear/files/2567766/aros-woboq.zip)

I have build aros with "bear -vvvv make" to produce a compile_commands.json file
[compile_commands.zip](https://github.com/rizsotto/Bear/files/2567734/compile_commands.zip)
Are there any extra options I need to add when I build other than just  'bear make'?
Thanks you for your time and patience.

**Comment by rizsotto** [comment] 2018-11-10 01:47
@stanman29 thanks for asking. I can't get what's the connection of your issue with this ticket?

I am not familiar with AROS project nor Metamake tool. Bear will intercept the compiler calls of your build. (Please read the documentation how it works and what are the edge cases when it might not.) Please create a new issue for specific question or problem you experience. (Also attach the stdout of verbose run, not only the output.)

To check if the compilation database is "inclomplete" or catch any problems with it, you need to inspect yourself. To check if the entries are the right ones, you can run the compilations with a python script you write, or run other tools which takes the compilation database as input (clang-format, clang-tidy, etc...) To see if the compilation database do contain all compilation is much harder. You need to know what files are needed to be there and compare it with the existing one... If you just want to make Woboq working and it fails, you might want to know why it failed. Check if the tool has any error report specific to the input. Or ask the tool writers for help to diagnose the issue.

**Comment by itzurabhi** [comment] 2019-11-13 10:17
> 
> 
> I have tested it extensively to determine what the problem is. Here is the flow of the calls:
> 
>     1. I (from an interactive shell) call `bear make`.
>        
>        * `make` is dynamically linked, and Bear generates debug output as appropriate. When a Makefile recipe calls `g++ ${WHATEVER}`, bear properly intercepts this.
> 
>     2. The Automake rules call a multi-line shell script as a single Make recipe line (see the backslashes at the end of the lines).
>        
>        * Make dispatches this, as with any other recipe line, to `/bin/sh`. `g++` is not at the start of the command, so Bear does not interpret this as a compiler call. Bear does properly intercept this call, and logs it with the rest of the execution reports.
> 
>     3. As my `/bin/sh` is statically linked, Bear cannot intercept the shell's `exec` calls, and does not know about the actual call to `g++`. Sub-make calls are inheriting the environment properly (I have confirmed Bear is generating the execution trace files for the calls to `/bin/sh`, even in sub-Makefiles), and non-Autotools builds comply perfectly with Bear, even when using sub-Makefiles.

I have a similar scenario,Please correct me if my understanding is incorrect.

My build system contains multiple layers of indirection ( as shell scripts ) to enable host agnostic build,cross compilation etc.

I found multiple **exec** calls in those script(s).

```
build.sh:
[..setup some environment...]
exec $buildTool $@

buildTool.sh:
[..setup some environment...]
[CC,CXX points to $compilerWrapper.sh]
exec $makeBinary $@

compilerWrapper.sh:
exec /path/to/the/real/clang/binaries/clang $@
```
/bin/sh [bash] is *not* statically linked 

`
/bin/bash: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=04eca96c5bf3e9a300952a29ef3218f00487d37b, stripped
`

Is @Web-eWorks mentioned issue (3) is affected here also ?

Host - Ubuntu 12, x64. 
Bear - master branch
Make - BSD Make
LLVM - 5.0

I get empty compilation commands json as output. There are no errors. It is clear that the library/tool cannot see the compiler invocations.

Will this also be fixed in 3.0 milestone mentioned , or does it require a separate effort ?

**Comment by rizsotto** [comment] 2019-11-13 11:35
Thanks for your follow up on this. No, the 3.0 version is still not released. :disappointed: 

But your case shall not suffer the same root cause (static binaries).

Could you confirm that the [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) of these files `build.sh`, `buildTool.sh` and `compilerWrapper.sh` is `bash`? If not could you check those files? Could you also check if those executables are the same architecture? (Typical problem is if 32 and 64 bit executables are mixed in the same build process.)

**Comment by itzurabhi** [comment] 2019-11-15 06:42
@rizsotto It was a internal ccache,env related issue. Fixed it.

You mentioned the mixing of 32 and 64 bit tools issue. Is there a solution for such situations ? 

Thanks for the quick response.

**Comment by rizsotto** [comment] 2019-11-16 00:26
@itzurabhi I'm glad that you have solved your problem.

Multilib issues and solutions are mentioned in the README file.

**Comment by rizsotto** [comment] 2020-09-14 00:25
There is a release candidate on master branch now, which suppose to fix this issue. Could you give it a try for that?

I'm closing this ticket now, but will re-open if the bug still there.

**Closed by rizsotto** 2020-09-14 00:25 UTC
